application: shareapp-1146
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /assets
  static_dir: assets

- url: /stylesheets
  static_dir: stylesheets

- url: /favicon\.ico
  static_files: favicon/flickr\.png
  upload: favicon/flickr\.png

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
